### ISSUE TITLE
"yarn analyze" says permission denied on mac

### ISSUE THREAD

**Issue by depsir** [exercism/javascript-analyzer#1]
I just downloaded the repo and following the README I did

```
yarn install
yarn build
yarn analyze pathToSolution
```

And I get 
```
/bin/sh: bin/analyze.sh: Permission denied
error Command failed with exit code 126.
```

I'm running zsh on mac os

**Comment by SleeplessByte** [comment]
This is a failure of the git + windows permission system. I will fix it in the repo.

**Comment by SleeplessByte** [comment]
Should be fixed by https://github.com/exercism/javascript-analyzer/commit/cf130b92ab8a718c64c516d13ed86d29853e3b64
