### ISSUE TITLE
Add proper linting

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/javascript-analyzer#11]
The current [.eslintrc](https://github.com/exercism/javascript-analyzer/blob/master/.eslintrc) is already set-up to be amended so we're checking `typescript` via eslint.

**Comment by zeckdude** [comment]
I'm confused what this issue is about. Can you please be more specific?
What do you mean `The current .eslintrc is already set-up to be amended`?

**Comment by SleeplessByte** [comment]
The current `.eslintrc` has:

```json
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "modules": true
    }
  }
}
```

It only has the parser configuration, but not actually a set of rules.

For example, we'll need to add [this](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin) plugin and then add `"extends": ["plugin:@typescript-eslint/recommended"]`. We'll probably have to think about using something like prettier, and add the appropriate plugins for that as well.

**Comment by depsir** [comment]
definitely prettier is a must in my opinion. many times it does funny stuff, especially in long lines but removes the entire formatting discussion from the table

we could add prettier with husky for precommit lint. maybe in this pr?

and also, why eslint over tslint?

**Comment by SleeplessByte** [comment]
`tslint` is soft-deprecated; the `eslint` typescript plugin is better maintained, has more features ánd means we can benefit of almost _all_ `eslint` integrations.

I'm okay with adding `husky` / `lint-staged` or similar -- usually have that when I use prettier anyway.
