### ISSUE TITLE
Incorrect Analysis: Semi-colon

### ISSUE THREAD

**Issue by mathstrains21** [exercism/javascript-analyzer#128]
**Describe the incorrectness**
I think the analyser should have pointed out my (deliberate) missing semi-colon.

**Which exercise**
Annalyn's Infiltration, but could probably happen on any

**Source file(s)**
annalyns-infiltration.js

```javascript
// source file: <slug>.js
// Any line that can end with ';' not ending with ';'
```

**Expected analysis**
I'd expect it to point out my missing semi-colon as it is a recommended thing to do.

**Additional context**

**Comment by junedev** [comment]
Thanks for pointing this out but on Exercism, we have the rule that the analyzers and mentors should not comment on stylistic choices made by user. And while probably a lot of people would agree with you that having semicolons is a good thing, it is still a stylistic choice. As an example for the opposing view, this linter/formatter was very popular in the Node.js community a while ago and would remove semicolons https://standardjs.com/.
