### ISSUE TITLE
Add analyzer for resistor-color

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/javascript-analyzer#13]
This issue is for discussion and assignment for the [`resistor-color`][exercise] core exercise in the `javascript` track. 

🔗 [implementation][exercise] | [mentor-notes][mentor-notes] | [problem-specification][problem-specification]

----

[mentor-notes]: https://github.com/exercism/website-copy/tree/master/tracks/javascript/exercises/resistor-color/mentoring.md
[exercise]: https://github.com/exercism/javascript/tree/master/exercises/resistor-color
[problem-specification]: https://github.com/exercism/problem-specifications/tree/master/exercises/resistor-color

This exercise introduces the student to [`Arrays`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) as well as showing that you
can export multiple bindings at once. Solutions using an `Object` will actively be discouraged as _speed_ is not a good reasoning here.

## Optimal solution(s)

```javascript
export const COLORS = [
  'black', 'brown', 'red', 'orange', 'yellow', 'green',
  'blue', 'violet', 'grey', 'white',
];

export const colorCode = color => COLORS.indexOf(color)
```

Approvable alternatives are:
- using an arrow function expression

## SHOULD comment and disapprove

Cases we _SHOULD_ comment on with this analyzer:
- Manually doing indexOf
- A set of conditionals or a switch
- Using the obscure `bind` to bind `Array.prototype.indexOf`

### COULD comment (tips)

Cases we _COULD_ comment on with this analyzer:
- Doing an `export` with a specifier (at the bottom of the file) can be done `export const` inline

**Comment by zeckdude** [comment]
@SleeplessByte I'd like to tackle this one.

**Comment by zeckdude** [comment]
I'm digging through the code and found the `fixtures` for each exercise. Got a few questions about those:

1. Where the test fixtures are coming from? I highly doubt those were manually added. There's 499 different approaches to solving the `two-fer` exercise in there. That's wild.
2. Where those fixtures are being used? I don't see any tests.

**Comment by SleeplessByte** [comment]
@zeckdude sure!

> Where are the test fixtures coming from? I highly doubt those were manually added. There's 499 different approaches to solving the two-fer exercise in there. That's wild.

These are the first 500 submission provided by Jeremy to me. I will ask Jeremy for `resistor-color` fixtures. If you run `node bin/batch-statistics you'll find the following metrics. Valid here means it was parseble and unique is unique solutions based on AST (**no** whitespace and no comments). ([original source message on slack][slack-stats])

|   total |  unique |   valid | invalid |
|--------:|--------:|--------:|--------:|
|     500 |     358 |     485 |      15 |

The statistics for the runner back then was this -- should be slightly different now:

## Statistics
|               Status | Count | Comments | Unique |    Avg | Median |   Total |
| --------------------:| -----:| --------:| ------:| ------:|-------:|--------:|
|    Approve (optimal) |     7 |        0 |      0 |  411ms |  414ms |      0s |
|    Approve (comment) |     0 |        0 |      0 |    0ms |    0ms |      0s |
| Disapprove (comment) |   355 |       16 |      7 |  413ms |  414ms |     14s |
|      Refer to mentor |   121 |        2 |      2 |  413ms |  415ms |      5s |
|                Total |   483 |       17 |      8 |  413ms |  415ms |     19s |

[slack-stats]: https://exercism-team.slack.com/archives/CFMEG1H0C/p1554125064020000?thread_ts=1554114746.016800&cid=CFMEG1H0C

> I can see the fixtures being used in the batch-runner to display general stats, but I think they would be useful for unit tests where we can assign an expected result type for each of the fixtures and if someone changes the code at a later time, the tests should catch it automatically if one of the tests no longer passes. Thoughts?

https://github.com/exercism/javascript-analyzer/issues/9 and specifically https://github.com/exercism/javascript-analyzer/issues/9#issuecomment-496215168

> I got the batch-runner to work by running node bin/batch-runner two-fer. It outputs a table with general data about each possible result type. I would really like to use the batch-runner to get a list of each fixture in each category. So then I see exactly in which category a specific fixture is being placed. Perhaps I'm missing something, but it appears that currently the only way to verify that certain fixtures are showing for a certain result type, you need to run it manually on a specific fixture. I'm hoping there's a better way, more automated way, than that. 🙏

I don't quite understand what you're asking for. The batch runner outputs the analysis.json files into the fixture directories which you can use. Would you like a table of "fixture number" -> "output status" -> "output comments"?

**Comment by SleeplessByte** [comment]
@zeckdude let me know if you have further comments. If not, I might go ahead and add a _minimal_ solution for `resistor-color` analyzer which you can use as a basis.

**Comment by SleeplessByte** [comment]
https://github.com/exercism/javascript-analyzer/pull/26

## Raw output

```json
{
  "invalid": 0,
  "valid": 498,
  "total": 498,
  "unique": 309
}
```

## Parsing statistics

This is the number of unique Abstract Syntax Trees after stripping commentary,
location data (whitespace) and other tokens.

|   total |  unique |   valid | invalid |
|--------:|--------:|--------:|--------:|
|     498 |     309 |     498 |       0 |

**Comment by SleeplessByte** [comment]
Since we have an initial analyzer, I'm closing this issue.
