### ISSUE TITLE
Add analyzer for resistor-color-duo

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/javascript-analyzer#14]
This issue is for discussion and assignment for the [`resistor-color-duo`][exercise] core exercise in the `javascript` track. 

🔗 [implementation][exercise] | [mentor-notes][mentor-notes] | [problem-specification][problem-specification]

----

[mentor-notes]: https://github.com/exercism/website-copy/tree/master/tracks/javascript/exercises/resistor-color-duo/mentoring.md
[exercise]: https://github.com/exercism/javascript/tree/master/exercises/resistor-color-duo
[problem-specification]: https://github.com/exercism/problem-specifications/tree/master/exercises/resistor-color-duo

This exercise introduces `map` and `join` to the student, as well as converting from and to `number`, and builds upon their knowledge of arrays from the previous exercise `resistor-color`.

## Optimal solution(s)

```javascript
export const COLORS = [
  'black', 'brown', 'red', 'orange', 'yellow', 'green', 'blue', 'violet',
  'grey', 'white',
];

function colorCode(color) {
  return COLORS.indexOf(color)
}

export function value(colors) {
  return Number(colors.map(colorCode).join(''))
}
```

A student who uses a `reducer` on the `reverse` of the input. This is a technique that comes from other languages as well as algorithm solving in university and is perfectly valid. It's one of the ways to do this without conversion to a `String`. Such a solution looks like this:

```javascript
export const COLORS = [
  'black', 'brown', 'red', 'orange', 'yellow', 'green', 'blue', 'violet',
  'grey', 'white',
];

export function value(colors) {
  return colors
    .reverse()
    .reduce(
      (value, color, i) => {
        // Find the index, then shift it in base 10, i places to the left
        return COLORS.indexOf(color) * (10 ** i) + value
      }
      , 0
    );
}
```

## SHOULD comment and disapprove

Cases we _SHOULD_ comment on with this analyzer:
- Comment to use the `resistor-color` solution instead of manually doing `indexOf`
- Comment to use the `resistor-color` solution instead of a set of conditionals or a switch
- Comment to use `Number` instead of `parseXXX`
- Comment to use `Number` instead of unary `+`
- Comment to use `join` instead of `reduce` (when using `reduce` to build the string)
- Comment to use `join` (converts to string) instead of explicit `toString`
- Comment to use an `Array` for `COLORS` instead of `Object`

### COULD comment (tips)

Cases we _COULD_ comment on with this analyzer:
- Doing an `export` with a specifier (at the bottom of the file) can be done `export const` inline

**Comment by SleeplessByte** [comment]
## Raw output

```json
{
  "invalid": 0,
  "valid": 494,
  "total": 494,
  "unique": 488
}
```

## Parsing statistics

This is the number of unique Abstract Syntax Trees after stripping commentary,
location data (whitespace) and other tokens.

|   total |  unique |   valid | invalid |
|--------:|--------:|--------:|--------:|
|     494 |     488 |     494 |       0 |

**Comment by crashb** [comment]
I have started working on this. My forked branch can be found [here](https://github.com/exercism/javascript-analyzer/compare/master...crashb:Issue-14) - it already contains some changes that will definitely need to be included (compile-time fixes and so on).

I have encountered a roadblock while trying to implement detection for the optimal map/join implementation, which may use a helper function. The roadblock is that I am not sure how to extract methods from the AST when they are not the main exported method. I suspect that this will require more util functions (extractAllMethods, extractTopLevelMethods or similar).

I also suspect that these util functions will require the declaration of a new type. Right now we have the following type declaration in `extract_main_method.ts`, which represents the main exported method:
```javascript
export type MainMethod<T extends string = string> =
  {
    id: Identifier & { name: T };
    parent: undefined | Node;
  } &
  (
    FunctionDeclaration
    | ArrowFunctionExpression
    | FunctionExpression
  )
```

I am not sure about how to go about adding a non-main `Method` type. Also, the `MainMethod` type should probably be changed to inherit from this new `Method` type once it is implemented.

**Comment by SleeplessByte** [comment]
I'm not _exactly_ sure what the question is, but I'll try to help you out!

A method is really one of the following things:

```typescript
// FunctionDeclaration
function foo () {}

// ArrowFunctionExpression
const a = function foo () {}

// FunctionExpression
const a = () => {}
```

There are no other _sane_ ways of creating a function in JavaScript, but technically you could also do it using `eval` or `new Function`:

```typescript
// NewExpression (with Identifier Function)
new Function("console.log('a')")
```

The `mainMethod` is _always exported_ (because that's how we find the main method), but all that adds is the _guarantee_ that it has a name. In other words, that it has an `Identifier`. 

These two things is what you see in the `MainMethod` type. If you wish to _type_ a generic method you can use:

```typescript
type MethodDeclaration = FunctionDeclaration
    | ArrowFunctionExpression
    | FunctionExpression
```

Which does _not_ have the guarantee that it has a name (and therefore does not have the guarantee that it can be called from somewhere else in the scope, other than in-line, or when bound to an argument). Functions are callable if they have an identifier, or if they are bound to an argument (which gives them an identifier).

-----

> The roadblock is that I am not sure how to extract methods from the AST when they are not the main exported method. I suspect that this will require more util functions (extractAllMethods, extractTopLevelMethods or similar).

I think the solution of `Gigasecond` might interest you. I would really like it if your solution could use the same structure (read: uses `IsolatedAnalyzer` and separates solution properties from the analyzer), but in general because it allows for _a helper variable/constant_, which is the same as in your case.

Instead of looking for functions that are not the main exports, I would suggest you try to match whatever AST you are looking for, and _there where a help method could be used_ check if the `Node` is an `Identifier`. If it _is_, use `findMethod(identifier)` or whatever helper, that checks the _entire AST_ for one of these:

- `FunctionDeclaration`
- `ArrowFunctionExpression`
- `FunctionExpression`

Now validate that the helper method is sane.

I hope this helps!

**Comment by SleeplessByte** [comment]
See #48 . If you'd still like to work on this, please rebase.
