### ISSUE TITLE
Incorrect Analysis: 

### ISSUE THREAD

**Issue by mmmmmrob** [exercism/javascript-analyzer#64]
**Describe the incorrectness**
The analyzer recommends approval of a function that doesn't return anything.

**Which exercise**
two-fer

**Source file(s)**
```javascript
// source file: two-fer.js
export const twoFer = (name = "you") => {
  console.log(`One for ${name}, one for me.`);
};
``` 
**Expected analysis**
It would be great if the analyzer could spot the lack of a return and prompt to disapprove with comments.

It would be great if the analyzer could spot the `console.log()` and prompt to disapprove with comments.

**Additional context**
The analyzer's been really helpful and is a great start :)

**Comment by SleeplessByte** [comment]
This now returns:

```json
{
  "comments": [
    {
      "comment": "javascript.general.no_value_returned",
      "params": {
        "export.name": "twoFer"
      },
      "type": "essential"
    }
  ]
}

```
